// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Account
{
    public int AccountId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }

    public int? AssociatedId { get; set; }

    public int? TotalPoint { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Customer Associated { get; set; }

    public virtual Restaurant AssociatedNavigation { get; set; }

    public virtual Role Role { get; set; }
}